name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: Install dependencies
            run: npm install
          - name: Check style
            run: npm run eslint
          - name: build
            run: npm run build
          - name: tests
            run: npm test
          - name: Install Playwright Browsers
            run: npx playwright install --with-deps chromium
          - name: Start server
            run: npm start &
          - name: Run Playwright tests
            run: npx playwright test
          - name: Trigger deployment
            run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
            if: github.event_name == 'push'
           # uses: sws2apps/render-deployment@v1.8.0
           # with:
           #   serviceId: ${{ secrets.RENDER_SERVICE_ID }}
           #   apiKey: ${{ secrets.RENDER_API_KEY }}
           #   multipleDeployment: false #optional, default true
    tag_release:
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4
          - name: Bump version and push tag
            uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
            if: ${{ github.event_name == 'push' && env.SKIP == 'false' }}
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              DEFAULT_BUMP: patch

    discord_status:
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
          - name: The job has succeeded
            uses: tsickert/discord-webhook@v5.3.0
            if: ${{ success() }}
            with:
              embed-color: 1176952
              username: GitHub
              embed-title: A new version of Pokedex deployed
              embed-description: Deploy to https://full-stack-open-pokedex-o3mk.onrender.com/ by @${{ toJson(github.actor) }}
              webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          - name: The job has failed
            uses: tsickert/discord-webhook@v5.3.0
            if: ${{ failure() }}
            with:
              embed-color: 16061203
              username: GitHub
              embed-title: Build failed
              embed-description: ${{ toJson(github.server_url) }}/${{ toJson(github.repository) }}/commit/${{toJson(github.sha)}} by @${{ toJson(github.actor) }} broke the build :(
              webhook-url: ${{ secrets.DISCORD_WEBHOOK }}