name: Schedule pipeline

on:
  schedule:
    - cron: '00 * * * *'
    - cron: '15 * * * *'
    - cron: '30 * * * *'
    - cron: '45 * * * *'
env:
  URL: https://full-stack-open-pokedex-o3mk.onrender.com

jobs:
  health-check_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{env.URL}}
      - name: The job has succeeded
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ success() }}
        with:
          embed-color: 1176952
          username: Health Check
          embed-title: Health check success
          embed-description: success ${{env.URL}} check
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: The job has failed
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ failure() }}
        with:
          embed-color: 16061203
          username: Health Check
          embed-title: Health check failed
          embed-description: failed ${{env.URL}} check
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}