name: Schedule pipeline

on:
  schedule:
    - cron: '00 * * * *'
    - cron: '15 * * * *'
    - cron: '30 * * * *'
    - cron: '45 * * * *'

jobs:
  health-check_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-o3mk.onrender.com/health
      - name: The job has succeeded
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ success() }}
        with:
          severity: info
          username: Health Check
          text: Health check failed
          description: success https://full-stack-open-pokedex-o3mk.onrender.com/health check
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: The job has failed
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
          severity: error
          username: Health Check
          text: Health check failed
          description: failed https://full-stack-open-pokedex-o3mk.onrender.com/health check
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}